version: '3'
services:
  web:
    image: wadehuang36/loadbalance-example
    ports:
      - 3000
  app:
    image: docker-engine-api-example
    build: .
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock